databases:
  - name: django_project_db
    databaseName: django_project
    user: django_project_user

services:
  - type: web
    name: django_project
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_project_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

  - type: cron
    name: daily_backup
    env: python
    schedule: "0 1 * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py backup_db"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_project_db
          property: connectionString